dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/install-docker-on-trusty.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - DOCKER_TEST_IMAGE=beegercorptest/$DOCKER_IMAGE_NAME
    - IMAGE_SIZE_THRESHOLD=35

install: true

stages:
  - name: Build
  - name: Test

jobs:
  include:
    - stage: Build
      env:
        - TAG=latest
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
      script:
        - docker build --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME
    - stage: Build
      env:
        - TAG=alpine-edge
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
      script:
        - docker build --build-arg ALPINE_VERSION=edge --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME
    - stage: Build
      env:
        - TAG=alpine-3.5
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
      script:
        - docker build --build-arg ALPINE_VERSION=3.5 --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME

    - stage: Test
      env:
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
        - TAG=latest
      script:
        - ./sh/ci/test.sh
    - stage: Test
      env:
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
        - TAG=alpine-edge
      script:
        - ./sh/ci/test.sh
    - stage: Test
      env:
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_TEST_IMAGE
        - TAG=alpine-3.5
      script:
        - ./sh/ci/test.sh
