dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/update-docker-on-travis.sh
  - sudo dockerd --experimental &
  - docker version

install: true

stages:
  - build
  - test


jobs:
  include:
    - stage: build
      script:
        - docker build --tag image --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i image -t 35
