dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/update-docker-on-travis.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - DOCKER_ORGANIZATION=beeglercorp
    - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME

install: true

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      env: TAG=latest
      script:
        - docker build --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t 35
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
            docker tag $DOCKER_IMAGE_NAME $DOCKER_PUBLIC_IMAGE_NAME:$TAG
            docker push $DOCKER_PUBLIC_IMAGE_NAME:$TAG;
          fi
    - stage: build
      env: TAG=alpine-edge
      script:
        - docker build --build-arg ALPINE_VERSION=edge --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t 35
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
            docker tag $DOCKER_IMAGE_NAME $DOCKER_PUBLIC_IMAGE_NAME:$TAG
            docker push $DOCKER_PUBLIC_IMAGE_NAME:$TAG;
          fi
    - stage: build
      env: TAG=alpine-3.5
      script:
        - docker build --build-arg ALPINE_VERSION=3.5 --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t 35
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
            docker tag $DOCKER_IMAGE_NAME $DOCKER_PUBLIC_IMAGE_NAME:$TAG
            docker push $DOCKER_PUBLIC_IMAGE_NAME:$TAG;
          fi
    - stage: test
      env: TAG=latest
      script:
        - docker run --rm $DOCKER_PUBLIC_IMAGE_NAME:$TAG --version
    - stage: test
      env: TAG=alpine-edge
      script:
        - docker run --rm $DOCKER_PUBLIC_IMAGE_NAME:$TAG --version
    - stage: test
      env: TAG=alpine-3.5
      script:
        - docker run --rm $DOCKER_PUBLIC_IMAGE_NAME:$TAG --version
