dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/install-docker-on-trusty.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - IMAGE_SIZE_THRESHOLD=35

install: true

stages:
  - name: Build

jobs:
  include:
    - stage: Build
      env:
        - ALPINE_VERSION=latest
        - TAG=latest
      script:
        - ./sh/ci/build.sh
    - stage: Build
      env:
        - ALPINE_VERSION=edge
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
    - stage: Build
      env:
        - ALPINE_VERSION=3.5
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
